### ISSUE TITLE
Badge bug

### ISSUE THREAD

**Issue by Arnphame** [Arnphame/laravelNuxt#6]
## Class
User

## Issue
We can create user with "Silver" badge even if his games_played count is less than 10.

## How to replicate?
Simply create a new user in the database with less than 10 games_played and give him "Silver" or better badge.

**Comment by arnasd** [comment]
Working on this case. Have you tried creating user with 100 games_played, but giving him Bronze badge?

**Comment by Arnphame** [comment]
@arnasd yes, this one works correctly.

**Comment by arnasd** [comment]
Great! 

Issue seems to be fixed, implemented new check-up before inserting data into database. Now it should be good.
