### ISSUE TITLE
Winner of the match

### ISSUE THREAD

**Issue by Arnphame** [Arnphame/laravelNuxt#7]
## Class
Game
Match

## Issue
Is there any way to choose witch team won the match? I think it would be great addition.

If admin sets the game to "Winner of the match", players should get +1 wins_count and it should display overall won matches in the site.

**Comment by arnasd** [comment]
Beta version will be released 2019-12-18. @Arnphame I will give you code to test it out

**Comment by Arnphame** [comment]
Code tested. Looks good

**Comment by arnasd** [comment]
Releasing Winner of the match to the production mode.
